export const projectsData = [
  {
    id: 1,
    name: "StellarEats",
    description: "A Swiggy clone for online food ordering.",
    date: "2024-07-12",
    demoLink: "https://stellareats.example.com",
    category: "Frontend",
  },
  {
    id: 2,
    name: "StellarHome",
    description: "A real estate website for property listing and discovery.",
    date: "2024-07-13",
    demoLink: "https://stellarhome.example.com",
    category: "Frontend",
  },
  {
    id: 3,
    name: "StellarConnect",
    description: "A LinkedIn clone for professional networking.",
    date: "2024-07-14",
    demoLink: "https://stellarconnect.example.com",
    category: "Frontend",
  },
  {
    id: 4,
    name: "StellarCode",
    description: "A LeetCode clone for solving coding challenges.",
    date: "2024-07-11",
    demoLink: "https://stellarcode.example.com",
    category: "Frontend",
  },
  {
    id: 5,
    name: "StellarPins",
    description: "A Pinterest clone for saving and sharing creative ideas.",
    date: "2024-07-21",
    demoLink: "https://stellarpins.example.com",
    category: "Backend",
  },
  {
    id: 6,
    name: "StellarChats",
    description: "A chatting app with real-time messaging and video calls.",
    date: "2024-07-21",
    demoLink: "https://stellarchats.example.com",
    category: "Backend",
  },
  {
    id: 7,
    name: "StellarDashboard",
    description: "An inventory management dashboard for businesses.",
    date: "2024-07-22",
    demoLink: "https://stellardashboard.example.com",
    category: "Backend",
  },
  {
    id: 8,
    name: "StellarJobs",
    description: "A job portal for finding and posting job opportunities.",
    date: "2024-07-23",
    demoLink: "https://stellarjobs.example.com",
    category: "Backend",
  },
  {
    id: 9,
    name: "StellarShop",
    description: "An e-commerce platform for buying and selling products.",
    date: "2024-07-24",
    demoLink: "https://stellarshop.example.com",
    category: "Full Stack",
  },
  {
    id: 10,
    name: "StellarCabs",
    description: "An Uber clone for cab booking and ride-sharing.",
    date: "2024-07-25",
    demoLink: "https://stellarcabs.example.com",
    category: "Full Stack",
  },
  {
    id: 11,
    name: "StellarPlan",
    description: "An AI-powered trip planner for travel enthusiasts.",
    date: "2024-07-26",
    demoLink: "https://stellarplan.example.com",
    category: "Software Engineering",
  },
  {
    id: 12,
    name: "StellarMedia",
    description: "A social media app for sharing posts and connecting with friends.",
    date: "2024-07-27",
    demoLink: "https://stellarmedia.example.com",
    category: "Software Engineering",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab:true },
  { label: "Projects", link: "/projects", icon: "projects", newTab: true },
  { label: "Contact", link: "/contact", icon: "contact", newTab: true },
  {
    label: "Github",
    link: "https://github.com/codERSunny812",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/sushil-pandey-8ab638209/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "X",
    link: "https://x.com/codeerasunny",
    icon: "twitter",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/SushilPandey__Resume.pdf",
    icon: "resume",
    newTab: true,
  },
];


