/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.gltf --transform 
Files: model.gltf [2.62MB] > /Users/sushilpandey/Downloads/sunny/gltf_embedded/model-transformed.glb [369.8KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Me(props) {
    const { nodes, materials } = useGLTF('/models/me.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes['tripo_node_2e34a820-83eb-4f85-9e23-5cc933613f4d'].geometry} material={materials['tripo_mat_2e34a820-83eb-4f85-9e23-5cc933613f4d']} />
        </group>
    )
}

useGLTF.preload('/models/me.glb')
